import type { BranchTranslations } from "./translationTypes";

export const BRANCH_TRANSLATIONS: BranchTranslations = {
  en: {
    titles: {
      list: "Branches",
      add: "Add Branch",
      edit: "Edit Branch",
      delete: "Delete Branch",
      management: "Branch Management",
    },
    fields: {
      name_en: "Branch Name (English)",
      name_ar: "Branch Name (Arabic)",
      branch_phone_number: "Phone Number",
      phone: "Phone",
      city: "City",
      address: "Address",
      location_link: "Location Link",
      status: "Status",
      branch_name: "Branch Name",
      name: "Branch Name",
      actions: "Actions",
      active: "Active",
      inactive: "Inactive",
    },
    actions: {
      create: "Create Branch",
      update: "Update Branch",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      search: "Search",
      addBranch: "Add Branch",
      confirmDelete: "Confirm Delete",
    },
    messages: {
      createSuccess: "Branch created successfully",
      updateSuccess: "Branch updated successfully",
      deleteSuccess: "Branch deleted successfully",
      createError: "Failed to create branch",
      updateError: "Failed to update branch",
      deleteError: "Failed to delete branch",
      deleteConfirmation: "Are you sure you want to delete",
      accessRestricted: "Access Restricted",
      noPermission: "Only Admins and Managers can access branch management.",
      cashierRestriction: "Cashiers do not have permission to manage branches.",
      subtitle: "Manage your organization branches",
      formDescription: "Add a new branch to your organization",
      editDescription: "Update branch information",
      deleteWarning: "This action cannot be undone.",
      activeStatus: "This branch is active and operational",
      inactiveStatus: "This branch is currently inactive",
      active: "Active",
      inactive: "Inactive",
      editTooltip: "Only Admin/Manager can edit",
      deleteTooltip: "Only Admin/Manager can delete",
      creating: "Creating...",
      updating: "Updating...",
    },
    validation: {
      required: "This field is required",
      invalidPhone: "Please enter a valid phone number",
    },
    placeholders: {
      name_en: "e.g. Main Branch",
      name_ar: "مثال: الفرع الرئيسي",
      phone: "+966 50 123 4567",
      city: "e.g. Riyadh",
      address: "Full branch address",
      location_link: "https://maps.google.com/?q=...",
      search: "Search branches...",
    },
  },
  ar: {
    titles: {
      list: "الفروع",
      add: "إضافة فرع",
      edit: "تعديل فرع",
      delete: "حذف فرع",
      management: "إدارة الفروع",
    },
    fields: {
      name_en: "اسم الفرع (إنجليزي)",
      name_ar: "اسم الفرع (عربي)",
      branch_phone_number: "رقم الهاتف",
      phone: "الهاتف",
      city: "المدينة",
      address: "العنوان",
      location_link: "رابط الموقع",
      status: "الحالة",
      branch_name: "اسم الفرع",
      name: "اسم الفرع",
      actions: "الإجراءات",
      active: "نشط",
      inactive: "غير نشط",
    },
    actions: {
      create: "إنشاء فرع",
      update: "تحديث الفرع",
      cancel: "إلغاء",
      delete: "حذف",
      edit: "تعديل",
      search: "بحث",
      addBranch: "إضافة فرع",
      confirmDelete: "تأكيد الحذف",
    },
    messages: {
      createSuccess: "تم إنشاء الفرع بنجاح",
      updateSuccess: "تم تحديث الفرع بنجاح",
      deleteSuccess: "تم حذف الفرع بنجاح",
      createError: "فشل إنشاء الفرع",
      updateError: "فشل تحديث الفرع",
      deleteError: "فشل حذف الفرع",
      deleteConfirmation: "هل أنت متأكد من حذف",
      accessRestricted: "الوصول مقيد",
      noPermission: "المسؤولين والمديرين فقط يمكنهم الوصول إلى إدارة الفروع.",
      cashierRestriction: "الكاشير ليس لديه صلاحية لإدارة الفروع.",
      subtitle: "إدارة فروع المنظمة",
      formDescription: "إضافة فرع جديد إلى منظمتك",
      editDescription: "تحديث معلومات الفرع",
      deleteWarning: "لا يمكن التراجع عن هذا الإجراء.",
      activeStatus: "هذا الفرع نشط وعامل",
      inactiveStatus: "هذا الفرع غير نشط حاليًا",
      active: "نشط",
      inactive: "غير نشط",
      editTooltip: "المسؤول/المدير فقط يمكنه التعديل",
      deleteTooltip: "المسؤول/المدير فقط يمكنه الحذف",
      creating: "جاري الإنشاء...",
      updating: "جاري التحديث...",
    },
    validation: {
      required: "هذا الحقل مطلوب",
      invalidPhone: "يرجى إدخال رقم هاتف صالح",
    },
    placeholders: {
      name_en: "مثال: Main Branch",
      name_ar: "مثال: الفرع الرئيسي",
      phone: "٠٥٠ ١٢٣ ٤٥٦٧ ٩٦٦+",
      city: "مثال: الرياض",
      address: "العنوان الكامل للفرع",
      location_link: "https://maps.google.com/?q=...",
      search: "بحث عن فرع...",
    },
  },
};
