import type { UserTranslations } from "./translationTypes";

export const USER_TRANSLATIONS: UserTranslations = {
  en: {
    titles: {
      management: "User Management",
      createUser: "Create New User",
      deleteUser: "Delete User",
      userDetails: "User Details",
    },
    fields: {
      name: "Name",
      email: "Email",
      password: "Password",
      phone: "Phone",
      address: "Address",
      picture: "Picture URL",
      designation: "Designation",
      branch: "Branch",
      status: "Status",
      actions: "Actions",
      logo: "Logo",
    },
    designations: {
      cashier: "Cashier",
      manager: "Manager",
      admin: "Admin",
      other: "Other",
    },
    actions: {
      addUser: "Add User",
      create: "Create User",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      search: "Search",
    },
    messages: {
      createSuccess: "User created successfully",
      deleteSuccess: "User deleted successfully",
      createError: "Failed to create user",
      deleteError: "Failed to delete user",
      deleteConfirmation: "Are you sure you want to delete",
      deleteWarning: "This action cannot be undone.",
      accessRestricted: "Access Restricted",
      noPermission: "Only Admins and Managers can access user management.",
      cashierRestriction: "Cashiers do not have permission to manage users.",
      createDescription: "Add a new user to your organization. Required fields are marked with *.",
      noUsers: 'No users yet. Click "Add User" to create one.',
      noMatchingUsers: "No matching users found",
      creating: "Creating...",
      deleting: "Deleting...",
      loadingBranches: "Loading branches...",
      active: "Active",
      inactive: "Inactive",
    },
    stats: {
      totalUsers: "Total Users",
      activeUsers: "Active Users",
      totalSpending: "Total Spending",
      totalPoints: "Total Points",
    },
    validation: {
      required: "This field is required",
      invalidEmail: "Please enter a valid email",
      minPassword: "Password must be at least 6 characters",
    },
    placeholders: {
      selectDesignation: "Select designation",
      selectBranch: "Select branch",
      searchUsers: "Search by name, email, or phone...",
      pictureUrl: "https://example.com/profile.jpg",
    },
  },
  ar: {
    titles: {
      management: "إدارة المستخدمين",
      createUser: "إنشاء مستخدم جديد",
      deleteUser: "حذف مستخدم",
      userDetails: "تفاصيل المستخدم",
    },
    fields: {
      name: "الاسم",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      phone: "الهاتف",
      address: "العنوان",
      picture: "رابط الصورة",
      designation: "المسمى الوظيفي",
      branch: "الفرع",
      status: "الحالة",
      actions: "الإجراءات",
      logo: "الشعار",
    },
    designations: {
      cashier: "كاشير",
      manager: "مدير",
      admin: "مسؤول",
      other: "أخرى",
    },
    actions: {
      addUser: "إضافة مستخدم",
      create: "إنشاء مستخدم",
      cancel: "إلغاء",
      delete: "حذف",
      edit: "تعديل",
      search: "بحث",
    },
    messages: {
      createSuccess: "تم إنشاء المستخدم بنجاح",
      deleteSuccess: "تم حذف المستخدم بنجاح",
      createError: "فشل إنشاء المستخدم",
      deleteError: "فشل حذف المستخدم",
      deleteConfirmation: "هل أنت متأكد من حذف",
      deleteWarning: "لا يمكن التراجع عن هذا الإجراء.",
      accessRestricted: "الوصول مقيد",
      noPermission: "المسؤولين والمديرين فقط يمكنهم الوصول إلى إدارة المستخدمين.",
      cashierRestriction: "الكاشير ليس لديه صلاحية لإدارة المستخدمين.",
      createDescription: "إضافة مستخدم جديد إلى منظمتك. الحقول المطلوبة مميزة بـ *.",
      noUsers: 'لا يوجد مستخدمون بعد. انقر على "إضافة مستخدم" لإنشاء واحد.',
      noMatchingUsers: "لم يتم العثور على مستخدمين مطابقين",
      creating: "جاري الإنشاء...",
      deleting: "جاري الحذف...",
      loadingBranches: "جاري تحميل الفروع...",
      active: "نشط",
      inactive: "غير نشط",
    },
    stats: {
      totalUsers: "إجمالي المستخدمين",
      activeUsers: "المستخدمون النشطون",
      totalSpending: "إجمالي الإنفاق",
      totalPoints: "إجمالي النقاط",
    },
    validation: {
      required: "هذا الحقل مطلوب",
      invalidEmail: "يرجى إدخال بريد إلكتروني صالح",
      minPassword: "يجب أن تكون كلمة المرور 6 أحرف على الأقل",
    },
    placeholders: {
      selectDesignation: "اختر المسمى الوظيفي",
      selectBranch: "اختر الفرع",
      searchUsers: "البحث بالاسم أو البريد الإلكتروني أو الهاتف...",
      pictureUrl: "https://example.com/profile.jpg",
    },
  },
};
